/*
 *
 * Dashboard constants
 *
 */

export const DASHBOARD_SET_LOADING = "DASHBOARD_SET_LOADING";
export const SET_COUNT_LOADING = "SET_COUNT_LOADING";
export const SET_DASHBOARD_DETAILS = "SET_DASHBOARD_DETAILS";
export const SET_INTERVIEW_DETAILS = "SET_INTERVIEW_DETAILS";
export const SET_EVENT_DETAILS = "SET_EVENT_DETAILS";
